tests failing. even when using solution.



(venv) windie@Davids-MBP flask-cupcakes % python -m unittest -v tests
test_create_cupcake (tests.CupcakeViewsTestCase) ... ERROR
test_get_cupcake (tests.CupcakeViewsTestCase) ... ERROR
test_list_cupcakes (tests.CupcakeViewsTestCase) ... ERROR

======================================================================
ERROR: test_create_cupcake (tests.CupcakeViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/tests.py", line 39, in setUp
    Cupcake.query.delete()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/flask_sqlalchemy/model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 218, in __call__
    sess = self.registry()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

======================================================================
ERROR: test_get_cupcake (tests.CupcakeViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/tests.py", line 39, in setUp
    Cupcake.query.delete()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/flask_sqlalchemy/model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 218, in __call__
    sess = self.registry()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

======================================================================
ERROR: test_list_cupcakes (tests.CupcakeViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/tests.py", line 39, in setUp
    Cupcake.query.delete()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/flask_sqlalchemy/model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 218, in __call__
    sess = self.registry()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/Users/windie/Documents/Springboard/SEC/Flask/flask-cupcakes/venv/lib/python3.7/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
(venv) windie@Davids-MBP flask-cupcakes % 
